### ISSUE TITLE
Unable to perform action because the specified Storyboard was never applied to this object for interactive control.

### ISSUE THREAD

**Issue by sekulicb** [zeluisping/LoadingIndicators.WPF#5]
Hi,

thanks for the library, works awesome. Just wanted to ask you something. When i use your loading indicator, i get the following warning in output window: 

System.Windows.Media.Animation Warning: 6 : Unable to perform action because the specified Storyboard was never applied to this object for interactive control.; Action='SetSpeedRatio'; Storyboard='System.Windows.Media.Animation.Storyboard'; Storyboard.HashCode='55397001'; Storyboard.Type='System.Windows.Media.Animation.Storyboard'; TargetElement='System.Windows.Controls.Border'; TargetElement.HashCode='36423148'; TargetElement.Type='System.Windows.Controls.Border'

"IsActive" property is done with binding, but SpeedRatio is just hardcoded in xaml and set to "2.0". Any thoughts on this?

All the best,
Bane

**Comment by 100GPing100** [comment]
Hey, sorry for the late reply, don't really have much personal time at the moment due to studies. This is probably a program in the control code, I will see if I can take a look at it. Maybe soon enough I'll be able to look at it all to review the library as a whole. Thank you for your support and for bringing this up, best of luck with your projects and as soon as I can I will take a look into the library, thank you!

**Comment by cb-dtf** [comment]
I experienced this as well today, although never had any issues before.
The icon loads fine to begin with, then later on it spits out this error, and then afterwards its unable to show the icon.

<pre>
Unable to perform action because the specified Storyboard was never applied to this object for interactive control.; Action='SetSpeedRatio'; Storyboard='System.Windows.Media.Animation.Storyboard'; Storyboard.HashCode='51826478'; Storyboard.Type='System.Windows.Media.Animation.Storyboard'; TargetElement='System.Windows.Controls.Border'; TargetElement.HashCode='63785121'; TargetElement.Type='System.Windows.Controls.Border'
</pre>

Any quick fixes or suggestions are most welcome. :)

**Comment by HonuDev** [comment]
Simple fix. In the OnApplyTemplate method, change:

`if (state.Name == "Active")`
to
`if (state.Name == "Active" && this.IsActive)`

**Comment by sekulicb** [comment]
Thanks for fix, although my problem disappeared by it self at some point in dev cycle. Not sure when but it was while back.

**Comment by 100GPing100** [comment]
Hey guys, sorry for the inactivity, the project is quite simple and I did not find the time that would justify being used on this.

@HonuDev Thank you for the solution, I will add that once I have some free time. Of course you'll be mentioned as solutioner, thank you! If you'd rather want to submit a pull request, feel free to do so. :smile:

**Comment by zeluisping** [comment]
I'm going to leave this issue open as I'd like to know if #6 already contains the fix for this.

@victorprocure #6 is your PR, what would be the status of this bug there?

**Comment by zeluisping** [comment]
I'm pretty sure this is fixed by #6 , closing
